apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1-app
  template:
    metadata:
      labels:
        app: task1-app
    spec:
      containers:
      - name: task1-app
        image: saadhanp/task-backend:latest
        ports:
        - containerPort: 8080
